### PR TITLE
[fixes #24] Time Traveler Detected!

### LINKED ISSUE #24: Test should be less sensitive to time.
Today, merely time passing causes test to fail, and fail in ways that are not simply update some minor details, rather they require more in-depth reworking of fixture data, and tests.

To address this, I am expanding on a core design decision, specifically the ability to parameterize the current date and time. Rather than this only being a capability for folks invoking the provided library functions, this will now become the CLI parameter `--date`. This will allow users to "time travel", and will allow our rigorous acceptance tests to operate on snapshots in time.

I do believe having some number of tests fail with regards to time passing might be ok, and as I do this work I will consider what that might be.

My current status is having the majority of the existing test failures resolved, with 4 more remaining. I expect once they are all resolved, I may need some additional time to polish, tidy-up, and potentially expand the test suite further.

A WIP PR will follow shortly.

### PR DESCRIPTION
**Pull request by stefanpenner**
fixes tests by adding an optional flag `--date="<override for the current date>"` which enables "time traveling" and utilizing it is tests that have date sensitive fixtures

```
--current-date="March 31, 2021"
--current-date="-3weeks" <-- 3 weeks ago
--current-date="1year" <-- 1 year from now
```

### CODE REVIEW

File: lib/cli.js [hunk 1]
```diff
@@ -3,23 +3,62 @@
...
+const parseDuration = require('parse-duration');
+/*
+ *
+ * convert a string representing a date into an actual date
+ * supports anything new Date(maybeDate) supports
+ *
+ * supports anything `parse-duration` supports:
+ *   -30 days === the date 30 days ago
+ */
+function processDate(inputDate) {
```
Comment (stefanpenner) [inline lib/cli.js:21]: TODO: unit test this function

File: README.md [hunk 2]
```diff
@@ -1,17 +1,23 @@
...
 
-
 ```sh
 npx supported <path/to/node_module>
 npx supported <[array/of/node_modules]>
 ```
 
+#### Optional Flags
+
+The `--date` flag enables a form of limited time travel, and attempts to run
```
Comment (scalvert) [inline README.md:13]: Should date be `--current-date`? I don't have a strong feeling here, but `date` is quite general. 🤷‍♂️

File: lib/cli.js [hunk 3]
```diff
@@ -3,23 +3,62 @@
...
 const { generateCsv } = require('../lib/output/csv-output');
+const parseDuration = require('parse-duration');
+/*
+ *
+ * convert a string representing a date into an actual date
+ * supports anything new Date(maybeDate) supports
+ *
+ * supports anything `parse-duration` supports:
+ *   -30 days === the date 30 days ago
+ */
```
Comment (scalvert) [inline lib/cli.js:20]: Any reason not to use jsdoc style comments?

File: lib/npm/config.js [hunk 4]
```diff
@@ -1,7 +1,7 @@
 'use strict';
 
 const execa = require('execa');
-const camelcaseKeys = require('camelcase-keys');
+const camelCaseKeys = require('camelcase-keys');
 
 module.exports = async function (cwd) {
   const child = execa.sync('npm', ['config', 'list', '--json'], {
```
Comment (scalvert) [inline lib/npm/config.js:7]: Why `execa.sync` in an async function?

I realize that execa is managing subprocesses, but using `child` here is a bit confusing to read. Would `result` be better?

```js
console.log(result.stdout);
// etc
```

**Review by scalvert — APPROVED** [review]
Left a few comments but otherwise LGTM.

File: README.md [hunk 5]
```diff
@@ -1,17 +1,23 @@
...
+the tools internal date calculations based on a specified date, rather then the
+current date.
+
+* `--date="March 31, 2011"` runs the tool as if it was March 31, 2021
+* `--date="-3 weeks"` runs the tool as if it was 3 weeks ago
+* `--date="3 weeks"` runs the tool as if it was 3 weeks from now
```
Comment (SparshithNR) [inline README.md:19]: It will be great if we can list/link to all types of available unit types. 
I found that the `prase-duration` library didn't provide a heading so that we can refer. I created a [PR](https://github.com/jkroso/parse-duration/pull/31) in the repo for the same.

**Review by SparshithNR — APPROVED** [review]
Looks good to me to accept one minor comment I have added.

File: README.md (hunk 5 above)
Comment (SparshithNR) [reply README.md:19]: PR is merged now.
We can use https://github.com/jkroso/parse-duration#available-unit-types-are

File: README.md (hunk 2 above)
Comment (stefanpenner) [reply README.md:13]: Ya, we should brain storm some ideas for the name. Date is a decent MVP name, but doesn't feel quite right.

File: lib/cli.js (hunk 3 above)
Comment (stefanpenner) [reply lib/cli.js:20]: More of an inline note, rather than API docs. I would prefer to convert the project to TS for better API docs derived from types etc. (which I believe we intend to do once this lands)

File: lib/npm/config.js (hunk 4 above)
Comment (stefanpenner) [reply lib/npm/config.js:7]: I can do a follow up PR that changes this, but given it isn't part of this existing PR I would like to keep it seperate.

re: `result` I feel that is ambiguous, but `child` isn't really accurate either as it represents the outcome of the child processes completion and no longer the child itself. Reading further, it seems that execa refers to this value as a [childProcessResult](https://github.com/sindresorhus/execa#childProcessResult) which is a mouth full.

Given that `result` does seem appropriate.

File: README.md (hunk 5 above)
Comment (stefanpenner) [reply README.md:21]: great idea

File: lib/cli.js (hunk 3 above)
Comment (scalvert) [reply lib/cli.js:20]: Fair.

File: lib/npm/config.js (hunk 4 above)
Comment (scalvert) [reply lib/npm/config.js:7]: 👍

File: README.md (hunk 2 above)
Comment (scalvert) [reply README.md:13]: Ya, I'm honestly not super opinionated about this, apart from the fact that `--date` is more ambiguous, and `--current-date` is slightly more specific to what it represents. My rule of thumb is generally "call it what it is", and not require folks to go to supporting documentation/usage to figure out how to use the flag.

Comment (stefanpenner) [reply README.md]: changed to `--current-date`

**Review by scalvert — APPROVED** [review]
