### PR TITLE
throw error if node version is below 8.*

### LINKED ISSUE #20: Running on unsupported versions of node can result in a difficult to understand failure.
I noticed that the support policy tool, due to the ora dependency, fails to run on versions of unsupported node such as node 8.

the error message is really not actionable:

```js
/Users/spenner/.npm/_npx/17b17d73ea3b4bfa/node_modules/ora/index.js:401
		} catch {
		        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/spenner/.npm/_npx/17b17d73ea3b4bfa/node_modules/supported/lib/cli.js:2:13)
```

At the very least would should fail fast, and provide a good error message. In theory, we can make this project work, even for old versions of node, but I don't think it would be worth our time.

### PR DESCRIPTION
**Pull request by SparshithNR**
fixes #20 
Screen Shot 2021-03-24 at 9 12 26 AM

### CODE REVIEW

**Review by asakusuma — CHANGES_REQUESTED** [review]
Should we just use the min engine field in package.json?

**Comment by SparshithNR** [comment]
when we use `npx` we do not have the `engine` field. 
so we have to check exactly the version which the user is running using the process.

File: lib/util.js [hunk 1]
```diff
@@ -139,11 +140,21 @@ class ProgressLogger {
   }
 }
 
+function checkNodeCompatibility(_nodeVersion) {
+  const nodeVersion = _nodeVersion || process.versions.node;
+  if (!semver.gtr(nodeVersion, '8.*')) {
```
Comment (stefanpenner) [inline lib/util.js:145]: Can we do both package.json's engine field as well?
Ideally, we read from that field, and validate here.

* the engines field is where we expect this
* NPX i believe doesn't respect the engines field

**Review by stefanpenner — CHANGES_REQUESTED** [review]

File: lib/util.js (hunk 1 above)
Comment (SparshithNR) [reply lib/util.js:145]: We are checking the node version of the current environment where the `supported` tool is run right.
To check if the package we are testing is above 8, we have a node test that checks the latest node LTS anyways.
I can run the `supported` command from anywhere in the machine, may run it from the `ember-cli` folder to check if `broccoli` is in the support policy. Where the `engine` field of `ember-cli` is irrelevant for us. 

Let me know if I am missing something,

Comment (asakusuma) [reply lib/util.js:145]: the engine field is not an ember-cli thing. it's a core node/package.json feature
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines

Comment (SparshithNR) [reply lib/util.js:145]: I understand that. 

What I am asking which `engine` property are we reading?

Comment (asakusuma) [reply lib/util.js:145]: I think there is value in setting the `engine` in package.json to inform other developers of the node requirement.

Other than that, if NPX ignores the package.json `engine` field, is there any value in doing anything (reading or setting) of any `engine` field?

Comment (SparshithNR) [reply lib/util.js:145]: yes.
if `A` adds `B` as dependency then `B` must meet `engine` requirements in `A`. This will still remain true in our case as we have set `supported's` package.json is pointing `>= 10.*`. 

This tool can be run without being added as a dependency, in that case, I feel it is redundant to check the `engine` and `process.versions.node`

Comment (stefanpenner) [reply lib/util.js:145]: we should compared supported's `packagein.json#engine` with `process.node` and error if `process.version` is not within the supported's `package.json#engine` contraints

Comment (SparshithNR) [reply lib/util.js]: Cool. That's true. Rather than comparing to a fixed node version, we can depend on this package's package.json#engine.

**Review by asakusuma — APPROVED** [review]
Thanks!

**Review by asakusuma — APPROVED** [review]

**Review by stefanpenner — APPROVED** [review]
perfect!

**Comment by stefanpenner** [comment]
+ supported@0.2.5
